# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  name: TEST-SELF-HOST

steps:
  # Use Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Use Node.js'

  # Install dependencies & build React app
  - script: |
      echo "Current directory: $(pwd)"
      echo "List files in directory:"
      ls -la

      echo "Node version:"
      node -v

      echo "NPM version:"
      npm -v

      echo "Installing dependencies..."
      npm install

      echo "Building the React app..."
      npm run build
    displayName: 'Install dependencies and build React app'
    workingDirectory: '$(Build.SourcesDirectory)'

  # Copy build output to staging
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'build'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy build to artifact staging'

  # Publish build artifact (optional, good for backup)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
    displayName: 'Publish build artifact'

# Deploy to local NGINX web root
  - script: |
      sudo apt update
      sudo apt install nginx -y
    displayName: 'Install NGINX'

  - script: |
      echo "Listing build output:"
      ls -la $(Build.ArtifactStagingDirectory)

      echo "Clearing existing NGINX root..."
      sudo rm -rf /var/www/html/*

      echo "Copying files..."
      sudo cp -r $(Build.ArtifactStagingDirectory)/* /var/www/html/

      echo "Deploy completed successfully!"
    displayName: Deploy to NGINX web root